export const SET_PROFESSIONS = 'SET_PROFESSIONS';
export const SET_PROFESSIONS_LIST = 'SET_PROFESSIONS_LIST';
export const CHECK_PROFESSION = 'CHECK_PROFESSION';
export const CHANGE_PROFESSION = 'CHANGE_PROFESSION';
export const POST_CHANGE_PROFESSIONS = 'POST_CHANGE_PROFESSIONS';
export const SET_TAG_LIST = 'SET_TAG_LIST';
